version: 2.1

orbs:
  maven: circleci/maven@0.0.12

workflows:
  maven_test:
    jobs:
      build:
        working_directory: ~/Kawer.tn

        steps:

          - checkout

          - restore_cache:
              keys:
                - Kawer.tn-{{ checksum "pom.xml" }}

          - run: mvn dependency:go-offline

          - save_cache:
              paths:
                - ~/.m2
              key: Kawer.tn-{{ checksum "pom.xml" }}

          - run: mvn package

          - store_test_results:
              path: target/surefire-reports

          - store_artifacts:
              path: target/Kawer.tn-0.0.1-SNAPSHOT.jar

          - maven/test # checkout, build, test, and upload test results
